import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  logs: [
    {
      id: 1,
      timestamp: 1718993201,
      text: "Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich.",
      tag: ["UserReq", "TCRes"],
      level: 90,
    },
    {
      id: 2,
      timestamp: 1719094967,
      text: "Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób.",
      tag: ["LLMRes", "TCReq", "UserRes"],
      level: 20,
    },
    {
      id: 3,
      timestamp: 1720468019,
      text: "Laptop został zepsuty przez przypadek. Spotkanie odbędzie się jutro rano. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Deszcz padał przez całą noc.",
      tag: ["TCReq", "LLMReq"],
      level: 100,
    },
    {
      id: 4,
      timestamp: 1723422462,
      text: "Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich. Słońce świeci mocno nad miastem. Pies biegał po parku przez godzinę. Programista pisze kod w nocy.",
      tag: ["LLMRes", "UserReq"],
      level: 30,
    },
    {
      id: 5,
      timestamp: 1720735650,
      text: "Samochód zatrzymał się na czerwonym świetle. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq"],
      level: 40,
    },
    {
      id: 6,
      timestamp: 1719893461,
      text: "Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich.",
      tag: ["LLMReq", "TCRes"],
      level: 80,
    },
    {
      id: 7,
      timestamp: 1722516830,
      text: "Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Deszcz padał przez całą noc.",
      tag: ["UserRes", "LLMRes", "TCReq"],
      level: 10,
    },
    {
      id: 8,
      timestamp: 1722150031,
      text: "Laptop został zepsuty przez przypadek. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Telefon zadzwonił nagle i zaskoczył wszystkich. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["TCRes", "LLMReq"],
      level: 70,
    },
    {
      id: 9,
      timestamp: 1720648322,
      text: "Deszcz padał przez całą noc. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Spotkanie odbędzie się jutro rano.",
      tag: ["LLMRes", "TCRes"],
      level: 60,
    },
    {
      id: 10,
      timestamp: 1722321654,
      text: "Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób.",
      tag: ["UserReq"],
      level: 50,
    },
    {
      id: 11,
      timestamp: 1719451214,
      text: "Laptop został zepsuty przez przypadek. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy.",
      tag: ["LLMRes", "TCReq", "TCRes"],
      level: 30,
    },
    {
      id: 12,
      timestamp: 1721849414,
      text: "Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich.",
      tag: ["LLMReq"],
      level: 100,
    },
    {
      id: 13,
      timestamp: 1719448910,
      text: "Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Deszcz padał przez całą noc.",
      tag: ["TCRes", "UserRes"],
      level: 20,
    },
    {
      id: 14,
      timestamp: 1720946648,
      text: "Laptop został zepsuty przez przypadek. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Telefon zadzwonił nagle i zaskoczył wszystkich. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["UserReq", "LLMRes"],
      level: 60,
    },
    {
      id: 15,
      timestamp: 1720991118,
      text: "Deszcz padał przez całą noc. Samochód zatrzymał się na czerwonym świetle. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy.",
      tag: ["TCReq"],
      level: 80,
    },
    {
      id: 16,
      timestamp: 1721010131,
      text: "Telefon zadzwonił nagle i zaskoczył wszystkich. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem. Pies biegał po parku przez godzinę. Laptop został zepsuty przez przypadek.",
      tag: ["LLMReq", "TCRes", "LLMRes"],
      level: 90,
    },
    {
      id: 17,
      timestamp: 1722374745,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Słońce świeci mocno nad miastem.",
      tag: ["TCReq", "UserRes"],
      level: 20,
    },
    {
      id: 18,
      timestamp: 1723104939,
      text: "Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Laptop został zepsuty przez przypadek. Samochód zatrzymał się na czerwonym świetle. Telefon zadzwonił nagle i zaskoczył wszystkich.",
      tag: ["LLMRes", "TCRes"],
      level: 100,
    },
    {
      id: 19,
      timestamp: 1721749042,
      text: "Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób.",
      tag: ["LLMReq", "UserReq"],
      level: 60,
    },
    {
      id: 20,
      timestamp: 1719496223,
      text: "Deszcz padał przez całą noc. Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle. Programista pisze kod w nocy.",
      tag: ["UserRes", "TCReq", "LLMRes"],
      level: 10,
    },
    {
      id: 21,
      timestamp: 1721235794,
      text: "Nowy projekt rozpoczął się w poniedziałek. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Telefon zadzwonił nagle i zaskoczył wszystkich. Słońce świeci mocno nad miastem.",
      tag: ["TCRes", "LLMRes"],
      level: 70,
    },
    {
      id: 22,
      timestamp: 1722517702,
      text: "Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Deszcz padał przez całą noc. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["UserReq", "TCReq"],
      level: 40,
    },
    {
      id: 23,
      timestamp: 1723298247,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Telefon zadzwonił nagle i zaskoczył wszystkich. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę.",
      tag: ["LLMReq", "UserRes"],
      level: 30,
    },
    {
      id: 24,
      timestamp: 1723400945,
      text: "Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy. Samochód zatrzymał się na czerwonym świetle. Kawa jest ulubionym napojem wielu osób. Pies biegał po parku przez godzinę.",
      tag: ["TCReq"],
      level: 50,
    },
    {
      id: 25,
      timestamp: 1722690250,
      text: "Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób. Laptop został zepsuty przez przypadek. Spotkanie odbędzie się jutro rano.",
      tag: ["TCRes", "UserReq", "LLMRes"],
      level: 90,
    },
    {
      id: 26,
      timestamp: 1723400568,
      text: "Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Telefon zadzwonił nagle i zaskoczył wszystkich. Deszcz padał przez całą noc. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["LLMReq"],
      level: 70,
    },
    {
      id: 27,
      timestamp: 1719713901,
      text: "Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek. Pies biegał po parku przez godzinę. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["TCRes", "UserRes"],
      level: 60,
    },
    {
      id: 28,
      timestamp: 1721553398,
      text: "Samochód zatrzymał się na czerwonym świetle. Deszcz padał przez całą noc. Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq", "LLMRes"],
      level: 20,
    },
    {
      id: 29,
      timestamp: 1720464186,
      text: "Telefon zadzwonił nagle i zaskoczył wszystkich. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób.",
      tag: ["LLMRes"],
      level: 30,
    },
    {
      id: 30,
      timestamp: 1719614357,
      text: "Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["UserRes", "TCRes"],
      level: 100,
    },
    {
      id: 31,
      timestamp: 1721590064,
      text: "Programista pisze kod w nocy. Telefon zadzwonił nagle i zaskoczył wszystkich. Pies biegał po parku przez godzinę. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "TCReq", "UserReq"],
      level: 80,
    },
    {
      id: 32,
      timestamp: 1719693274,
      text: "Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Laptop został zepsuty przez przypadek. Deszcz padał przez całą noc. Programista pisze kod w nocy.",
      tag: ["TCRes"],
      level: 40,
    },
    {
      id: 33,
      timestamp: 1721751754,
      text: "Pies biegał po parku przez godzinę. Słońce świeci mocno nad miastem. Telefon zadzwonił nagle i zaskoczył wszystkich. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["LLMRes", "UserRes"],
      level: 30,
    },
    {
      id: 34,
      timestamp: 1723211325,
      text: "Deszcz padał przez całą noc. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy. Słońce świeci mocno nad miastem. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq", "UserReq"],
      level: 60,
    },
    {
      id: 35,
      timestamp: 1720576496,
      text: "Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Laptop został zepsuty przez przypadek.",
      tag: ["TCRes"],
      level: 10,
    },
    {
      id: 36,
      timestamp: 1723387477,
      text: "Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Deszcz padał przez całą noc. Telefon zadzwonił nagle i zaskoczył wszystkich. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "UserRes"],
      level: 90,
    },
    {
      id: 37,
      timestamp: 1720230087,
      text: "Programista pisze kod w nocy. Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq"],
      level: 70,
    },
    {
      id: 38,
      timestamp: 1722711634,
      text: "Pies biegał po parku przez godzinę. Nowy projekt rozpoczął się w poniedziałek. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["UserRes", "LLMRes"],
      level: 100,
    },
    {
      id: 39,
      timestamp: 1723021107,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Telefon zadzwonił nagle i zaskoczył wszystkich.",
      tag: ["TCRes", "LLMReq"],
      level: 20,
    },
    {
      id: 40,
      timestamp: 1720475692,
      text: "Deszcz padał przez całą noc. Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["LLMRes", "UserReq"],
      level: 60,
    },
    {
      id: 41,
      timestamp: 1720777606,
      text: "Kawa jest ulubionym napojem wielu osób. Laptop został zepsuty przez przypadek. Pies biegał po parku przez godzinę. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["TCReq"],
      level: 40,
    },
    {
      id: 42,
      timestamp: 1720602446,
      text: "Nowy projekt rozpoczął się w poniedziałek. Telefon zadzwonił nagle i zaskoczył wszystkich. Samochód zatrzymał się na czerwonym świetle. Deszcz padał przez całą noc. Programista pisze kod w nocy.",
      tag: ["LLMRes", "UserRes", "TCRes"],
      level: 50,
    },
    {
      id: 43,
      timestamp: 1719893476,
      text: "Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Słońce świeci mocno nad miastem. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób.",
      tag: ["TCReq", "UserReq"],
      level: 80,
    },
    {
      id: 44,
      timestamp: 1722733152,
      text: "Samochód zatrzymał się na czerwonym świetle. Laptop został zepsuty przez przypadek. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Deszcz padał przez całą noc.",
      tag: ["LLMReq", "TCRes"],
      level: 100,
    },
    {
      id: 45,
      timestamp: 1722347262,
      text: "Kawa jest ulubionym napojem wielu osób. Telefon zadzwonił nagle i zaskoczył wszystkich. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Laptop został zepsuty przez przypadek.",
      tag: ["TCReq", "LLMRes"],
      level: 70,
    },
    {
      id: 46,
      timestamp: 1722409981,
      text: "Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy.",
      tag: ["TCRes", "UserReq"],
      level: 90,
    },
    {
      id: 47,
      timestamp: 1721949487,
      text: "Deszcz padał przez całą noc. Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Nowy projekt rozpoczął się w poniedziałek. Pies biegał po parku przez godzinę.",
      tag: ["LLMRes", "UserRes"],
      level: 10,
    },
    {
      id: 48,
      timestamp: 1721721930,
      text: "Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq", "LLMReq", "UserReq"],
      level: 80,
    },
    {
      id: 49,
      timestamp: 1721884455,
      text: "Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem.",
      tag: ["TCRes", "UserRes"],
      level: 30,
    },
    {
      id: 50,
      timestamp: 1722090129,
      text: "Samochód zatrzymał się na czerwonym świetle. Pies biegał po parku przez godzinę. Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["LLMRes", "TCReq"],
      level: 60,
    },
    {
      id: 51,
      timestamp: 1720674705,
      text: "Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle. Laptop został zepsuty przez przypadek.",
      tag: ["UserReq", "TCRes"],
      level: 100,
    },
    {
      id: 52,
      timestamp: 1723342555,
      text: "Nowy projekt rozpoczął się w poniedziałek. Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób.",
      tag: ["LLMReq", "UserRes"],
      level: 10,
    },
    {
      id: 53,
      timestamp: 1722657302,
      text: "Spotkanie odbędzie się jutro rano. Deszcz padał przez całą noc. Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["TCReq"],
      level: 70,
    },
    {
      id: 54,
      timestamp: 1721247113,
      text: "Programista pisze kod w nocy. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Spotkanie odbędzie się jutro rano. Laptop został zepsuty przez przypadek.",
      tag: ["LLMRes", "TCRes", "UserReq"],
      level: 90,
    },
    {
      id: 55,
      timestamp: 1723152432,
      text: "Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle. Deszcz padał przez całą noc. Nowy projekt rozpoczął się w poniedziałek. Programista pisze kod w nocy.",
      tag: ["TCReq", "LLMReq"],
      level: 40,
    },
    {
      id: 56,
      timestamp: 1720576962,
      text: "Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Laptop został zepsuty przez przypadek.",
      tag: ["UserRes", "LLMRes"],
      level: 20,
    },
    {
      id: 57,
      timestamp: 1720081525,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem.",
      tag: ["TCRes"],
      level: 30,
    },
    {
      id: 58,
      timestamp: 1720360253,
      text: "Samochód zatrzymał się na czerwonym świetle. Spotkanie odbędzie się jutro rano. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "UserReq", "TCReq"],
      level: 60,
    },
    {
      id: 59,
      timestamp: 1721104154,
      text: "Kawa jest ulubionym napojem wielu osób. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Programista pisze kod w nocy.",
      tag: ["LLMRes", "UserRes"],
      level: 50,
    },
    {
      id: 60,
      timestamp: 1721940209,
      text: "Deszcz padał przez całą noc. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Słońce świeci mocno nad miastem.",
      tag: ["TCRes", "LLMReq", "TCReq"],
      level: 80,
    },
    {
      id: 61,
      timestamp: 1721738215,
      text: "Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano.",
      tag: ["UserRes", "TCReq"],
      level: 100,
    },
    {
      id: 62,
      timestamp: 1723347333,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Deszcz padał przez całą noc. Programista pisze kod w nocy. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["LLMRes", "TCRes"],
      level: 10,
    },
    {
      id: 63,
      timestamp: 1720826902,
      text: "Pies biegał po parku przez godzinę. Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Słońce świeci mocno nad miastem.",
      tag: ["TCReq", "LLMReq"],
      level: 70,
    },
    {
      id: 64,
      timestamp: 1721576342,
      text: "Deszcz padał przez całą noc. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["TCRes", "UserReq"],
      level: 40,
    },
    {
      id: 65,
      timestamp: 1723325576,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["LLMRes"],
      level: 30,
    },
    {
      id: 66,
      timestamp: 1721406138,
      text: "Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób.",
      tag: ["TCReq", "UserReq"],
      level: 60,
    },
    {
      id: 67,
      timestamp: 1720909467,
      text: "Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Kawa jest ulubionym napojem wielu osób. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano.",
      tag: ["LLMRes", "TCRes"],
      level: 80,
    },
    {
      id: 68,
      timestamp: 1719848741,
      text: "Laptop został zepsuty przez przypadek. Spotkanie odbędzie się jutro rano. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["TCReq"],
      level: 100,
    },
    {
      id: 69,
      timestamp: 1720473378,
      text: "Programista pisze kod w nocy. Samochód zatrzymał się na czerwonym świetle. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "TCRes", "UserRes"],
      level: 10,
    },
    {
      id: 70,
      timestamp: 1723282555,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem.",
      tag: ["TCReq", "LLMReq"],
      level: 70,
    },
    {
      id: 71,
      timestamp: 1722735430,
      text: "Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy.",
      tag: ["UserReq", "TCRes"],
      level: 40,
    },
    {
      id: 72,
      timestamp: 1723404783,
      text: "Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Deszcz padał przez całą noc. Pies biegał po parku przez godzinę. Słońce świeci mocno nad miastem.",
      tag: ["TCReq", "LLMRes"],
      level: 30,
    },
    {
      id: 73,
      timestamp: 1719887803,
      text: "Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Słońce świeci mocno nad miastem.",
      tag: ["TCRes"],
      level: 60,
    },
    {
      id: 74,
      timestamp: 1722475476,
      text: "Pies biegał po parku przez godzinę. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "UserReq", "TCReq"],
      level: 100,
    },
    {
      id: 75,
      timestamp: 1722641937,
      text: "Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Laptop został zepsuty przez przypadek.",
      tag: ["TCRes", "LLMRes"],
      level: 10,
    },
    {
      id: 76,
      timestamp: 1720741216,
      text: "Samochód zatrzymał się na czerwonym świetle. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["TCReq"],
      level: 70,
    },
    {
      id: 77,
      timestamp: 1723251675,
      text: "Deszcz padał przez całą noc. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq", "TCRes", "UserRes"],
      level: 40,
    },
    {
      id: 78,
      timestamp: 1721399274,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Samochód zatrzymał się na czerwonym świetle. Pies biegał po parku przez godzinę.",
      tag: ["TCReq", "LLMRes"],
      level: 30,
    },
    {
      id: 79,
      timestamp: 1722678520,
      text: "Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem.",
      tag: ["LLMReq"],
      level: 60,
    },
    {
      id: 80,
      timestamp: 1720576542,
      text: "Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy.",
      tag: ["TCReq", "TCRes"],
      level: 80,
    },
    {
      id: 81,
      timestamp: 1721868425,
      text: "Deszcz padał przez całą noc. Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["LLMReq", "TCRes"],
      level: 100,
    },
    {
      id: 82,
      timestamp: 1721190968,
      text: "Kawa jest ulubionym napojem wielu osób. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek. Spotkanie odbędzie się jutro rano.",
      tag: ["UserReq", "TCReq"],
      level: 10,
    },
    {
      id: 83,
      timestamp: 1721537846,
      text: "Pies biegał po parku przez godzinę. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["TCRes", "LLMRes"],
      level: 50,
    },
    {
      id: 84,
      timestamp: 1723355848,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób.",
      tag: ["TCReq", "UserRes"],
      level: 20,
    },
    {
      id: 85,
      timestamp: 1722537349,
      text: "Deszcz padał przez całą noc. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Samochód zatrzymał się na czerwonym świetle. Programista pisze kod w nocy.",
      tag: ["LLMRes"],
      level: 30,
    },
    {
      id: 86,
      timestamp: 1721597431,
      text: "Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["TCRes", "LLMReq"],
      level: 60,
    },
    {
      id: 87,
      timestamp: 1722099781,
      text: "Pies biegał po parku przez godzinę. Samochód zatrzymał się na czerwonym świetle. Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["TCReq", "UserReq"],
      level: 80,
    },
    {
      id: 88,
      timestamp: 1721682322,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek. Kawa jest ulubionym napojem wielu osób.",
      tag: ["LLMRes", "TCRes"],
      level: 100,
    },
    {
      id: 89,
      timestamp: 1722562649,
      text: "Samochód zatrzymał się na czerwonym świetle. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano.",
      tag: ["TCReq", "LLMReq"],
      level: 10,
    },
    {
      id: 90,
      timestamp: 1720776821,
      text: "Laptop został zepsuty przez przypadek. Kawa jest ulubionym napojem wielu osób. Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Spotkanie odbędzie się jutro rano.",
      tag: ["LLMRes", "TCRes"],
      level: 70,
    },
    {
      id: 91,
      timestamp: 1722876644,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["UserReq", "TCReq"],
      level: 40,
    },
    {
      id: 92,
      timestamp: 1720504110,
      text: "Samochód zatrzymał się na czerwonym świetle. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób. Laptop został zepsuty przez przypadek. Programista pisze kod w nocy.",
      tag: ["TCRes", "LLMRes"],
      level: 30,
    },
    {
      id: 93,
      timestamp: 1723124406,
      text: "Spotkanie odbędzie się jutro rano. Nowy projekt rozpoczął się w poniedziałek. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["TCReq", "LLMReq", "UserRes"],
      level: 60,
    },
    {
      id: 94,
      timestamp: 1720167661,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Kawa jest ulubionym napojem wielu osób. Spotkanie odbędzie się jutro rano. Słońce świeci mocno nad miastem.",
      tag: ["LLMRes"],
      level: 80,
    },
    {
      id: 95,
      timestamp: 1722168882,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Nowy projekt rozpoczął się w poniedziałek.",
      tag: ["TCReq", "UserReq"],
      level: 100,
    },
    {
      id: 96,
      timestamp: 1722526611,
      text: "Spotkanie odbędzie się jutro rano. Kawa jest ulubionym napojem wielu osób. Deszcz padał przez całą noc. Słońce świeci mocno nad miastem. Programista pisze kod w nocy.",
      tag: ["TCRes", "LLMReq"],
      level: 10,
    },
    {
      id: 97,
      timestamp: 1720768016,
      text: "Nowy projekt rozpoczął się w poniedziałek. Słońce świeci mocno nad miastem. Kawa jest ulubionym napojem wielu osób. Laptop został zepsuty przez przypadek. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["LLMRes", "TCRes"],
      level: 70,
    },
    {
      id: 98,
      timestamp: 1723095454,
      text: "Deszcz padał przez całą noc. Programista pisze kod w nocy. Spotkanie odbędzie się jutro rano. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób.",
      tag: ["UserReq", "TCReq"],
      level: 40,
    },
    {
      id: 99,
      timestamp: 1722092401,
      text: "Laptop został zepsuty przez przypadek. Słońce świeci mocno nad miastem. Nowy projekt rozpoczął się w poniedziałek. Kawa jest ulubionym napojem wielu osób. Samochód zatrzymał się na czerwonym świetle.",
      tag: ["LLMReq", "TCRes"],
      level: 30,
    },
    {
      id: 100,
      timestamp: 1720753789,
      text: "Spotkanie odbędzie się jutro rano. Programista pisze kod w nocy. Pies biegał po parku przez godzinę. Kawa jest ulubionym napojem wielu osób. Słońce świeci mocno nad miastem.",
      tag: ["TCReq", "LLMRes"],
      level: 60,
    },
  ],
};

export const logSlice = createSlice({
  name: "log",
  initialState,
  reducers: {},
});

export const logActions = logSlice.actions;
export default logSlice.reducer;
